global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bike-station'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bike-station:8081']

  - job_name: 'rental-reservation'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rental-reservation:8082']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mercado-pago-gateway:8083']

  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['192.168.1.14:9323']
